### ISSUE TITLE
ARDUINO=100 always added as define to g++

### ISSUE THREAD

**Issue by jgfoster** [Arduino-CI/arduino_ci#176]
## cpp_library.rb:327 hard-codes `-DARDUINO=100` on command line

- OS: macOS
- `ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]`
- `Bundler version 1.17.2`
- `arduino_ci (0.3.0)`
- `Apple clang version 12.0.0 (clang-1200.0.32.2)`
- Arduino IDE version: 1.8.13
- `java version "11.0.7" 2020-04-14 LTS`

## `.arduino-ci.yaml`:
```
platforms:
  mega2560:
    board: arduino:avr:mega:cpu=atmega2560
    package: arduino:avr
    gcc:
      features:
      defines:
        - __AVR_ATmega2560__
        # added this line
        - ARDUINO_CI
        - ARDUINO=10813
      warnings:
      flags:

unittest:
  platforms:
      - mega2560

compile:
  platforms:
    - mega2560
```

## Warning
```
In file included from <built-in>:399:
<command line>:4:9: warning: 'ARDUINO' macro redefined [-Wmacro-redefined]
#define ARDUINO 10813
        ^
<command line>:1:9: note: previous definition is here
#define ARDUINO 100
        ^
1 warning generated.
```
