### ISSUE TITLE
Arduino CI seems to not handle dependencies between imported Arduino Libraries

### ISSUE THREAD

**Issue by cherbel** [Arduino-CI/arduino_ci#192]
I am writing tests for a library A (TankControllerLib), and it imports library B (MAX31865) that has a dependance on library C (BusIO). When I wrote tests for library B, I included library C in .arduino-ci.yml, and it was able to find and use my modified library C. Now, I've included B and C as prerequisites for library A, and when library B is compiled, the header for library C is not found. 

```
In file included from /Users/c/Desktop/Fall 2020/CPTR 450 Software Engineering/Projects/TankControllerLib/src/Devices/TempProbe_TC.cpp:5:
In file included from /Users/c/Documents/Arduino/libraries/Adafruit_MAX31865/src/Adafruit_MAX31865_CI.h:2:
/Users/c/Documents/Arduino/libraries/Adafruit_MAX31865/src/Adafruit_MAX31865.h:63:10: fatal error: 'Adafruit_SPIDevice.h' file not found
#include <Adafruit_SPIDevice.h>
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Here is my .arduino_ci.yml for the TankControllerLib:
```
unittest:
    platforms:
        - mega2560
    libraries:
      - "LiquidCrystal"
      - "Adafruit BusIO"
      - "Adafruit_MAX31865"
```

Here is my .arduino_ci.yml for MAX31865:
```
unittest:
  platforms:
    - mega2560
  testfiles:
    reject:
      - "Common.cpp"
  libraries:
    - "Adafruit BusIO"
```

Issue report prepared with @jgfoster
