### ISSUE TITLE
Properly handle libraries with spaces in names, when installed as custom libraries

### ISSUE THREAD

**Issue by ianfixes** [Arduino-CI/arduino_ci#222]
If a library with a space in the name is requested, we expect it to be stored on disk as having an underscore substituted for the space.  Detection of already-installed libraries breaks somewhat in this case.  Consider the following:

```yaml
unittest:
  platforms:
    - mega2560
  libraries:
    - "Adafruit BusIO"
    # - "Adafruit_BusIO"    <= This works if you have the library pre-installed
```
