### ISSUE TITLE
support git-url and zip-path in library installation

### ISSUE THREAD

**Issue by ianfixes** [Arduino-CI/arduino_ci#278]
via https://github.com/arduino/arduino-cli/pull/648

`arduino-cli lib install <library name>` now supports `--git-url <url>` and `--zip-path <path>`.

the config should be expanded to allow something like this:

```yaml
compile:
  libraries:
    - someLibrary      # String value: let the Arduino library manager figure it out
    - localLibrary:    # Hash
      zip_path: ./wherever/it/is.zip
    - gitLibrary:      # Hash
        git_url: git@git.com:me/gitLibrary.git
```
