### ISSUE TITLE
Expose build-properties flag

### ISSUE THREAD

**Issue by ianfixes** [Arduino-CI/arduino_ci#279]
via https://github.com/arduino/arduino-cli/pull/1044

`./arduino-cli compile -b arduino:avr:uno --build-property="build.extra_flags=\"-DMY_DEFINE=\"hello world\"\"" /home/user/Arduino/MySketch`

This should probably appear in the config as a new entry `build_properties`

```yaml
compile:
  build_properties:
    - "build.extra_flags=\"-DMY_DEFINE=\"hello world\"\""
    - "build.extra_flags=-DPIN=2 \"-DMY_DEFINE=\"hello world\"\""
    - build.extra_flags=-DPIN=2 --build-property="compiler.cpp.extra_flags=\"-DMY_DEFINE=\"hello world\"\"" 
```
