### ISSUE TITLE
Poor error reporting for undefined platforms

### ISSUE THREAD

**Issue by ianfixes** [Arduino-CI/arduino_ci#282]
via https://github.com/Arduino-CI/action/issues/21

Consider this compilation config

```yaml
compile:
  platforms:
    - this_doesnt_exist
```

This produces `NoMethodError: undefined method `[]' for nil:NilClass error` instead of a sensible message about the platform not being defined.  This is a regression in the error communication to the user.
