### ISSUE TITLE
NoMethodError: undefined method `map' for nil:NilClass

### ISSUE THREAD

**Issue by QuentinN42** [Arduino-CI/arduino_ci#295]
Running `Arduino-CI/action@stable-1.x` result in `NoMethodError` :

I use the default workflow :
```
name: Arduino_CI

on: [pull_request]

jobs:
  arduino_ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Arduino-CI/action@stable-1.x
```
And my project is ok for [`arduino-lint` action](https://github.com/marketplace/actions/arduino-arduino-lint-action) :
```
CI-test/
├── CI-test.ino
├── examples
│   └── example.c
├── README.md
└── test
    └── test.c
```
But I have always this issue :
```
================================================================================
Beginning the next phase of testing...           Compilation of example sketches
bundler: failed to load command: /action/bundle/ruby/2.6.0/bin/arduino_ci.rb (/action/bundle/ruby/2.6.0/bin/arduino_ci.rb)
NoMethodError: undefined method `map' for nil:NilClass
  /action/bundle/ruby/2.6.0/gems/arduino_ci-1.3.0/lib/arduino_ci/cpp_library.rb:135:in `example_sketches'
  /action/bundle/ruby/2.6.0/gems/arduino_ci-1.3.0/exe/arduino_ci.rb:450:in `perform_example_compilation_tests'
  /action/bundle/ruby/2.6.0/gems/arduino_ci-1.3.0/exe/arduino_ci.rb:536:in `<top (required)>'
  /action/bundle/ruby/2.6.0/bin/arduino_ci.rb:23:in `load'
  /action/bundle/ruby/2.6.0/bin/arduino_ci.rb:23:in `<top (required)>'
```
