### ISSUE TITLE
Can RP2040 build environment be supported?

### ISSUE THREAD

**Issue by RobTillaart** [Arduino-CI/arduino_ci#329]
Is it possible to support the RP2040 build environment?

Would be appreciated 

PR - https://github.com/RobTillaart/MCP_DAC/pull/16

**Comment by RobTillaart** [comment]
Found how to do it.

.arduino-ci.yml
```
platforms:
  pico:
    board: rp2040:rp2040:rpipico
    package: rp2040:rp2040
    gcc:
      features:
      defines:
        - ARDUINO_ARCH_RP2040
      warnings:
      flags:

packages:
  rp2040:rp2040:
    url: https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json


compile:
  # Choosing to run compilation tests on 2 different Arduino platforms
  platforms:
    - uno
    # - due
    # - zero
    # - leonardo
    # - m4
    # - esp32
    # - esp8266
    # - mega2560
    - pico
```
