### ISSUE TITLE
running in gitlab CI

### ISSUE THREAD

**Issue by daniel-mohr** [Arduino-CI/arduino_ci#332]
## System

- URL of your Arduino project: https://gitlab.com/daniel_mohr/fast_samd21_tc

## Issue Summary

How to run/use `arduino_ci.rb` correct in a CI pipeline on gitlab?

I tried several methods to get `arduino_ci.rb` running. Unfortunately I was only able to run it using ubuntu:18.04 which is pretty old and not a solution for the future.

Using the following works:
```yml
arduino_ci_ubuntu_1804:
  image:
    name: ubuntu:18.04
  script:
    - date
    - apt-get update
    - $APT_GET_INSTALL ruby build-essential
    - gem install bundler arduino_ci
    - export EXPECT_UNITTESTS=1
    - export EXPECT_EXAMPLES=1
    - arduino_ci.rb
```

But using a newer ubuntu image works not:
```yml
arduino_ci_ubuntu_latest:
  image:
    name: ubuntu:latest
  script:
    - date
    - apt-get update
    - $APT_GET_INSTALL ruby build-essential
    - gem install bundler arduino_ci
    - export EXPECT_UNITTESTS=1
    - export EXPECT_EXAMPLES=1
    - arduino_ci.rb
```
This leads to:
```
$ gem install bundler arduino_ci
Successfully installed bundler-2.3.25
Parsing documentation for bundler-2.3.25
Installing ri documentation for bundler-2.3.25
Done installing documentation for bundler after 0 seconds
Successfully installed rubyzip-1.3.0
Successfully installed os-1.1.4
Successfully installed arduino_ci-1.3.0
Parsing documentation for rubyzip-1.3.0
Installing ri documentation for rubyzip-1.3.0
Parsing documentation for os-1.1.4
Installing ri documentation for os-1.1.4
Parsing documentation for arduino_ci-1.3.0
Installing ri documentation for arduino_ci-1.3.0
Done installing documentation for rubyzip, os, arduino_ci after 1 seconds
4 gems installed
$ export EXPECT_UNITTESTS=1
$ export EXPECT_EXAMPLES=1
$ arduino_ci.rb
                           .                  __  ___
                   _, ,_  _| , . * ._   _    /  `  | 
                  (_| [ `(_] (_| | [ ) (_)   \__. _|_   v1.3.0
Host OS... /var/lib/gems/3.0.0/gems/arduino_ci-1.3.0/lib/arduino_ci/arduino_downloader.rb:111:in `initialize': No such file or directory @ rb_sysopen - https://github.com/arduino/arduino-cli/releases/download/0.13.0/arduino-cli_0.13.0_Linux_64bit.tar.gz (Errno::ENOENT)
	from /var/lib/gems/3.0.0/gems/arduino_ci-1.3.0/lib/arduino_ci/arduino_downloader.rb:111:in `open'
	from /var/lib/gems/3.0.0/gems/arduino_ci-1.3.0/lib/arduino_ci/arduino_downloader.rb:111:in `download'
	from /var/lib/gems/3.0.0/gems/arduino_ci-1.3.0/lib/arduino_ci/arduino_downloader.rb:144:in `block in execute'
	from /var/lib/gems/3.0.0/gems/arduino_ci-1.3.0/lib/arduino_ci/arduino_downloader.rb:136:in `loop'
	from /var/lib/gems/3.0.0/gems/arduino_ci-1.3.0/lib/arduino_ci/arduino_downloader.rb:136:in `execute'
	from /var/lib/gems/3.0.0/gems/arduino_ci-1.3.0/lib/arduino_ci/arduino_installation.rb:57:in `force_install'
	from /var/lib/gems/3.0.0/gems/arduino_ci-1.3.0/lib/arduino_ci/arduino_installation.rb:43:in `autolocate!'
	from /var/lib/gems/3.0.0/gems/arduino_ci-1.3.0/exe/arduino_ci.rb:497:in `<top (required)>'
	from /usr/local/bin/arduino_ci.rb:25:in `load'
	from /usr/local/bin/arduino_ci.rb:25:in `<main>'
                                                                linux
Attempting to download Arduino 0.13.0 package with open-uri
Cleaning up project directory and file based variables
ERROR: Job failed: exit code 1
```

Very similar using debian:latest leads to (I skipped some parts):

```
$ arduino_ci.rb
                           .                  __  ___
                   _, ,_  _| , . * ._   _    /  `  | 
                  (_| [ `(_] (_| | [ ) (_)   \__. _|_   v1.3.0
Host OS... /var/lib/gems/2.7.0/gems/arduino_ci-1.3.0/exe/arduino_ci.rb:155:in `warn': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /usr/lib/ruby/2.7.0/open-uri.rb:18:in `open'
	from /var/lib/gems/2.7.0/gems/arduino_ci-1.3.0/lib/arduino_ci/arduino_downloader.rb:111:in `download'
	from /var/lib/gems/2.7.0/gems/arduino_ci-1.3.0/lib/arduino_ci/arduino_downloader.rb:144:in `block in execute'
	from /var/lib/gems/2.7.0/gems/arduino_ci-1.3.0/lib/arduino_ci/arduino_downloader.rb:136:in `loop'
	from /var/lib/gems/2.7.0/gems/arduino_ci-1.3.0/lib/arduino_ci/arduino_downloader.rb:136:in `execute'
	from /var/lib/gems/2.7.0/gems/arduino_ci-1.3.0/lib/arduino_ci/arduino_installation.rb:57:in `force_install'
	from /var/lib/gems/2.7.0/gems/arduino_ci-1.3.0/lib/arduino_ci/arduino_installation.rb:43:in `autolocate!'
	from /var/lib/gems/2.7.0/gems/arduino_ci-1.3.0/exe/arduino_ci.rb:497:in `<top (required)>'
	from /usr/local/bin/arduino_ci.rb:23:in `load'
	from /usr/local/bin/arduino_ci.rb:23:in `<main>'
```

But using the repository from `arduino_ci` seems to work:

```yml
arduino_ci_latest_debian_latest:
  image:
    name: debian:latest
  script:
    - date
    - apt-get update
    - $APT_GET_INSTALL ruby build-essential git
    - echo "source 'https://rubygems.org'" > Gemfile
    - echo -n "gem 'arduino_ci', git:" >> Gemfile
    - echo " 'https://github.com/Arduino-CI/arduino_ci.git'" >> Gemfile
    - cat Gemfile
    - gem install bundler
    - bundle install
    - export EXPECT_UNITTESTS=1
    - export EXPECT_EXAMPLES=1
    - bundle exec arduino_ci.rb
```

This leads to:

```
$ bundle exec arduino_ci.rb
                           .                  __  ___
                   _, ,_  _| , . * ._   _    /  `  | 
                  (_| [ `(_] (_| | [ ) (_)   \__. _|_   v1.3.0
Host OS...                                                                 linux
Attempting to download Arduino 0.13.0 package with open-uri.
Extracting archive with tar
Located arduino-cli binary...                                  /root/arduino-cli
Creating libraries directory...                                                ✓
Environment variable CUSTOM_INIT_SCRIPT...                                    ''
Environment variable USE_SUBDIR...                                            ''
Installing library under test...                                               ✓
Library installed at...                   /root/Arduino/libraries/fast_samd21_tc
================================================================================
Beginning the next phase of testing...                              Unit testing
...
Failures: 0
Cleaning up project directory and file based variables
Job succeeded
```
