### ISSUE TITLE
libraries: "SoftwareSerial" does not work.

### ISSUE THREAD

**Issue by RobTillaart** [Arduino-CI/arduino_ci#346]
Repo: https://github.com/RobTillaart/MHZCO2

Has an example that uses SoftwareSerial and it compiles well on the desktop.
However in the build they fail to build

I have added the following in the yml file but it still 
```
  libraries:
    - "SoftwareSerial"
 ```
 
Note that 
So for now I just commented the SoftwareSerial line, so that the other things are build/tested.

----- 

error output - https://github.com/RobTillaart/MHZCO2/actions/runs/3950260138/jobs/6762557012

```
Discovered example sketch...                                  MHZCO2_serial1.ino
Using configuration override from example... /home/runner/work/MHZCO2/MHZCO2/examples/MHZCO2_serial1/.arduino-ci.yml
Wildcard architecture in library.properties, using configured platforms... 
    mega2560
...Wildcard architecture in library.properties, using configured platforms      
Board package arduino:avr has a defined URL...                                 ✓
Installing board package arduino:avr...                                        ✓
Installing dependency of <compile/libraries>: 'SoftwareSerial'...              ✗
This may indicate a problem with your configuration; halting here
Failures: 1
========== Last backend command (if relevant):
 $  /home/runner/arduino-cli --format json lib install --no-deps SoftwareSerial
========== Backend Stdout:

========== Backend Stderr:
Error installing SoftwareSerial: Library 'SoftwareSerial' not found
```

**Comment by ianfixes** [comment]
This seems related to a problem I had earlier with `Ethernet`: https://github.com/Arduino-CI/arduino_ci/issues/192#issuecomment-726815021

I can't recall how I fixed that one, but this comment is my "note to self".

**Comment by ianfixes** [comment]
The main question here is what the official project will try to do if you list `SoftwareSerial` as a dependency in `library.properties`.  Is that just a no-op?  @per1234 I'm hoping you can add more insight than what I would get if I try to just reverse engineer the behavior.

**Comment by per1234** [comment]
"**SoftwareSerial**" is a [platform bundled library](https://arduino.github.io/arduino-cli/dev/platform-specification/#platform-bundled-libraries). It is distributed as a component of some (but not all) boards platforms such as `arduino:avr`:

https://github.com/arduino/ArduinoCore-avr/tree/master/libraries/SoftwareSerial

The [`depends` field of `library.properties`](https://arduino.github.io/arduino-cli/dev/library-specification/#libraryproperties-file-format) can only be used to list libraries that are in the Arduino Library Manager index. The "SoftwareSerial" library is not in the Arduino Library Manager index, so it does not make sense to add it to the `depends` field. The closest thing is the `architectures` field, where you could specify compatibility only with the architectures (e.g., `architectures=avr,megaavr`) of the specific boards platforms that provide a "SoftwareSerial" library.

**Comment by RobTillaart** [comment]
In practice that means I have to disable the compile tests for examples using SWS for those boards. 
It might be worth adding a few lines on this in the section about **libraries**

Thanks @per1234 for this insight

**Comment by ianfixes** [comment]
Thanks @per1234, that's extremely helpful information here.  I was thinking about how my library should approach this, because if I were to maintain my own mapping of "platform bundled libraries" in this project, I am in danger of being perpetually out of sync with the "ground truth" known by the Arduino environment itself.  Still, is there any information I might be able to use from the configuration (e.g. [`default.yml`](https://github.com/Arduino-CI/arduino_ci/blob/master/misc/default.yml)) to check the local filesystem for a platform?   Is that a wildly unstable idea?

@RobTillaart, you might also be able to just provide an example-specific override using an `.arduino-ci.yml` file in that example's directory, that omits the `SoftwareSerial` dependency.

**Comment by RobTillaart** [comment]
@ianfixes 
used the following ```.arduino-ci.yml``` to compile the example for the platforms that support SoftwareSerial

See https://github.com/RobTillaart/MHZCO2/tree/master/examples/MHZCO2_sw_serial

```yml
platforms:
  rpipico:
    board: rp2040:rp2040:rpipico
    package: rp2040:rp2040
    gcc:
      features:
      defines:
        - ARDUINO_ARCH_RP2040
      warnings:
      flags:

packages:
  rp2040:rp2040:
    url: https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json

compile:
  #  Choosing to run compilation tests on 2 different Arduino platforms
  platforms:
    - uno
    # - due      //  has no SoftwareSerial
    # - zero     //  has no SoftwareSerial
    - leonardo
    # - m4       //  has no SoftwareSerial
    # - esp32    //  has no SoftwareSerial
    - esp8266
    - mega2560
    - rpipico
  #  external libraries
  libraries:
    # - "SoftwareSerial" does not work as it is build in.

```
