### ISSUE TITLE
Add CircleCI example 

### ISSUE THREAD

**Issue by ianfixes** [Arduino-CI/arduino_ci#77]
## Feature Request

Add CircleCI to this project and report its status in the README

### Example Code

[`.circleci/config.yml`](https://github.com/TomohiroHayashi/arduino_test1/commit/6b1bf3d1b94de5b668f809eb1ebfbc0bde91cb46) via @TomohiroHayashi
```yaml
version: 2
jobs:
  build:
    machine: true    
    steps:
      - checkout

      - run:
          name: install and execute
          command: |
            bundle install
            bundle exec arduino_ci_remote.rb
```

### Example README.md section

Platform | Travis CI | AppVeyor | CircleCI
---------|:----------|:---------|:--------
OSX      | [![OSX Build Status](http://badges.herokuapp.com/travis/ianfixes/arduino_ci?env=BADGE=osx&label=build&branch=master)](https://travis-ci.org/ianfixes/arduino_ci) | | NEW BADGE HERE
Linux    | [![Linux Build Status](http://badges.herokuapp.com/travis/ianfixes/arduino_ci?env=BADGE=linux&label=build&branch=master)](https://travis-ci.org/ianfixes/arduino_ci) | | NEW BADGE HERE
Windows  | | [![Windows Build status](https://ci.appveyor.com/api/projects/status/8f6e39dea319m83q/branch/master?svg=true)](https://ci.appveyor.com/project/ianfixes/arduino-ci) |
